/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Center: typeof import('./src/components/Center.vue')['default']
    DragBox: typeof import('./src/components/DragBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Space: typeof import('./src/components/Space.vue')['default']
    UploadSuccessDialog: typeof import('./src/components/UploadSuccessDialog.vue')['default']
  }
}
